experiment_id: Office
device_id: google_pixel_4
hardware_id: arduino_vcap_com3
environment_id: Office
router_id: Xiaomi
apps:
  # - bilibili_android
  # - youtube_android
  # - tiktok_android
  # - vimeo_android
  - twitch_android
  # - youku_android
  # - huya_android
  # - ted_android
app_warmup_sec: 60
duration_sec: 1200
repetitions: 1
output_root: data/raw/Office
rf_collector:
  base_url: http://127.0.0.1:8000
  smooth: true
  show_raw: true
  smooth_window: 11
