experiment_id: Collected
device_id: samsung_galaxy_S10
hardware_id: arduino_vcap_com3
environment_id: office
router_id: TP-Link
apps:
  - ebay_android
  - amazon_shopping_android
  - aliexpress_android
  - temu_android
  - shein_android
  - lazada_android
  - zalora_android
  - taobao_android
app_warmup_sec: 60
duration_sec: 1200
repetitions: 1
output_root: data/raw/Collected
rf_collector:
  base_url: http://127.0.0.1:8000
  smooth: true
  show_raw: true
  smooth_window: 11
